packages:
  - apps/*
  - packages/*
  - services/*

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
